# Generated by Django 4.2.10 on 2024-02-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('image', models.ImageField(max_length=9999, upload_to='media')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_text', models.TextField(null=True)),
            ],
        ),
    ]
