# Generated by Django 4.2.7 on 2023-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='image',
            field=models.ImageField(max_length=99999999, upload_to='media'),
        ),
    ]
