# Generated by Django 4.2.7 on 2023-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagehistory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
