# Generated by Django 4.2.7 on 2023-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagehistory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='converted_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagehistory',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
